from typing import cast

from openai import OpenAI
from langchain_core.embeddings import Embeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from openai.types.chat import ChatCompletionMessageParam
from dotenv import load_dotenv
import gradio as gr
import os

load_dotenv()

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

client = OpenAI(
    api_key=os.environ["API_KEY"],
)


class OpenAIEmbeddings(Embeddings):
    def __init__(self, client, model="text-embedding-3-small"):
        self.client = client
        self.model = model

    def embed_documents(self, texts):
        response = self.client.embeddings.create(model=self.model, input=texts)
        return [item.embedding for item in response.data]

    def embed_query(self, text):
        response = self.client.embeddings.create(model=self.model, input=text)
        return response.data[0].embedding


## Document loader
def document_loader(file):
    file_path = file.name if hasattr(file, "name") else file
    loader = PyPDFLoader(file_path)
    loaded_document = loader.load()
    return loaded_document

## Text splitter
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=50,
        length_function=len,
    )
    chunks = text_splitter.split_documents(data)
    return chunks


## Embedding model
def openai_embedding():
    return OpenAIEmbeddings(client)

## Vector db
def vector_database(chunks):
    embedding_model = openai_embedding()
    vectordb = Chroma.from_documents(
        documents=chunks,
        embedding=embedding_model)
    return vectordb

## Retriever
def retriever(file):
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    retriever = vectordb.as_retriever(search_kwargs={"k": 4})
    return retriever

## QA Chain
def retriever_qa(file, query):
    retriever_obj = retriever(file)
    docs = retriever_obj.invoke(query)
    context = "\n\n".join(doc.page_content for doc in docs)
    messages = cast(
        list[ChatCompletionMessageParam],
        [
            {
                "role": "system",
                "content": "You are a helpful assistant that answers questions using only the provided document context. If the context does not contain the answer, say you do not know.",
            },
            {
                "role": "user",
                "content": f"Context:\n{context}\n\nQuestion: {query}",
            },
        ],
    )
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=messages,
        temperature=0.5,
        max_tokens=256,
    )
    return response.choices[0].message.content

# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"), 
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Answer"),
    title="QA Bot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

# Launch the app
rag_application.launch(server_name="0.0.0.0", server_port=7860)
